version: '3.8'
services:
  pasarela:
    build:
      context: .
      dockerfile: Dockerfile-pasarela
    ports:
      - 8090:8090
    environment:
      - zuul.routes.restaurantes.url=http://restaurantes:8080
      - zuul.routes.opiniones.url=http://opiniones-rest:5193

  restaurantes-rest:
    build:
      context: .
      dockerfile: Dockerfile-restaurante
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTION_STRING="mongodb://arso:arso@ac-v8ez3vj-shard-00-00.kzwz6ia.mongodb.net:27017,ac-v8ez3vj-shard-00-01.kzwz6ia.mongodb.net:27017,ac-v8ez3vj-shard-00-02.kzwz6ia.mongodb.net:27017/?ssl=true&replicaSet=atlas-b3t6zg-shard-0&authSource=admin&retryWrites=true&w=majority"

  opiniones-rest:
    build:
      context: ./opiniones-rest
      dockerfile: Dockerfile
    ports:
      - 5193:5193
      - 7054:7054
    environment:
      - MONGODB_CONNECTION_STRING="mongodb://arso:arso@ac-v8ez3vj-shard-00-00.kzwz6ia.mongodb.net:27017,ac-v8ez3vj-shard-00-01.kzwz6ia.mongodb.net:27017,ac-v8ez3vj-shard-00-02.kzwz6ia.mongodb.net:27017/?ssl=true&replicaSet=atlas-b3t6zg-shard-0&authSource=admin&retryWrites=true&w=majority"

networks:
  default:
    external: true
    name: mynetwork
